//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.12 at 11:31:34 PM CET 
//


package dynamicrefactoring.plugin.xml.refactorings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mechanismType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mechanismType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="preconditions" type="{}preconditionsType"/>
 *         &lt;element name="actions" type="{}actionsType"/>
 *         &lt;element name="postconditions" type="{}postconditionsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mechanismType", propOrder = {
    "preconditions",
    "actions",
    "postconditions"
})
public class MechanismType {

    @XmlElement(required = true)
    protected PreconditionsType preconditions;
    @XmlElement(required = true)
    protected ActionsType actions;
    @XmlElement(required = true)
    protected PostconditionsType postconditions;

    /**
     * Gets the value of the preconditions property.
     * 
     * @return
     *     possible object is
     *     {@link PreconditionsType }
     *     
     */
    public PreconditionsType getPreconditions() {
        return preconditions;
    }

    /**
     * Sets the value of the preconditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreconditionsType }
     *     
     */
    public void setPreconditions(PreconditionsType value) {
        this.preconditions = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link ActionsType }
     *     
     */
    public ActionsType getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionsType }
     *     
     */
    public void setActions(ActionsType value) {
        this.actions = value;
    }

    /**
     * Gets the value of the postconditions property.
     * 
     * @return
     *     possible object is
     *     {@link PostconditionsType }
     *     
     */
    public PostconditionsType getPostconditions() {
        return postconditions;
    }

    /**
     * Sets the value of the postconditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostconditionsType }
     *     
     */
    public void setPostconditions(PostconditionsType value) {
        this.postconditions = value;
    }

}
