//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.12 at 11:31:34 PM CET 
//


package dynamicrefactoring.plugin.xml.refactorings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dynamicrefactoring.plugin.xml.refactorings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Refactoring_QNAME = new QName("", "refactoring");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dynamicrefactoring.plugin.xml.refactorings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link PreconditionType }
     * 
     */
    public PreconditionType createPreconditionType() {
        return new PreconditionType();
    }

    /**
     * Create an instance of {@link RefactoringType }
     * 
     */
    public RefactoringType createRefactoringType() {
        return new RefactoringType();
    }

    /**
     * Create an instance of {@link ClassificationType }
     * 
     */
    public ClassificationType createClassificationType() {
        return new ClassificationType();
    }

    /**
     * Create an instance of {@link ExampleType }
     * 
     */
    public ExampleType createExampleType() {
        return new ExampleType();
    }

    /**
     * Create an instance of {@link MechanismType }
     * 
     */
    public MechanismType createMechanismType() {
        return new MechanismType();
    }

    /**
     * Create an instance of {@link ImageType }
     * 
     */
    public ImageType createImageType() {
        return new ImageType();
    }

    /**
     * Create an instance of {@link PreconditionsType }
     * 
     */
    public PreconditionsType createPreconditionsType() {
        return new PreconditionsType();
    }

    /**
     * Create an instance of {@link CategorizationType }
     * 
     */
    public CategorizationType createCategorizationType() {
        return new CategorizationType();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link InformationType }
     * 
     */
    public InformationType createInformationType() {
        return new InformationType();
    }

    /**
     * Create an instance of {@link InputsType }
     * 
     */
    public InputsType createInputsType() {
        return new InputsType();
    }

    /**
     * Create an instance of {@link PostconditionsType }
     * 
     */
    public PostconditionsType createPostconditionsType() {
        return new PostconditionsType();
    }

    /**
     * Create an instance of {@link InputType }
     * 
     */
    public InputType createInputType() {
        return new InputType();
    }

    /**
     * Create an instance of {@link KeywordsType }
     * 
     */
    public KeywordsType createKeywordsType() {
        return new KeywordsType();
    }

    /**
     * Create an instance of {@link PostconditionType }
     * 
     */
    public PostconditionType createPostconditionType() {
        return new PostconditionType();
    }

    /**
     * Create an instance of {@link ActionsType }
     * 
     */
    public ActionsType createActionsType() {
        return new ActionsType();
    }

    /**
     * Create an instance of {@link ExamplesType }
     * 
     */
    public ExamplesType createExamplesType() {
        return new ExamplesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefactoringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "refactoring")
    public JAXBElement<RefactoringType> createRefactoring(RefactoringType value) {
        return new JAXBElement<RefactoringType>(_Refactoring_QNAME, RefactoringType.class, null, value);
    }

}
