//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.26 at 09:06:20 AM CET 
//


package dynamicrefactoring.plugin.xml.classifications;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dynamicrefactoring.plugin.xml.classifications package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Classifications_QNAME = new QName("", "classifications");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dynamicrefactoring.plugin.xml.classifications
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CategoriesType }
     * 
     */
    public CategoriesType createCategoriesType() {
        return new CategoriesType();
    }

    /**
     * Create an instance of {@link ClassificationsType }
     * 
     */
    public ClassificationsType createClassificationsType() {
        return new ClassificationsType();
    }

    /**
     * Create an instance of {@link ClassificationType }
     * 
     */
    public ClassificationType createClassificationType() {
        return new ClassificationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassificationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "classifications")
    public JAXBElement<ClassificationsType> createClassifications(ClassificationsType value) {
        return new JAXBElement<ClassificationsType>(_Classifications_QNAME, ClassificationsType.class, null, value);
    }

}
